# Generated by Django 4.1.5 on 2023-03-07 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysilantapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serNumM', models.CharField(max_length=30)),
                ('serNumE', models.CharField(max_length=30)),
                ('serNumT', models.CharField(max_length=30)),
                ('serNumDA', models.CharField(max_length=30)),
                ('serNumSA', models.CharField(max_length=30)),
                ('NumSupContract', models.CharField(max_length=30)),
                ('dateShipmentFactory', models.DateField()),
                ('consignee', models.CharField(max_length=30)),
                ('addressOperation', models.CharField(max_length=128)),
                ('equipment', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='ModelDriveAxle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelSteeringAxle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelTransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('workOrder', models.CharField(max_length=30)),
                ('dateWorkOrder', models.DateField()),
                ('machine', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='mysilantapp.machine')),
                ('serviceCompany', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysilantapp.servicecompany')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysilantapp.typemaintenance')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='modelDA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mysilantapp.modeldriveaxle'),
        ),
        migrations.AddField(
            model_name='machine',
            name='modelE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mysilantapp.modelengine'),
        ),
        migrations.AddField(
            model_name='machine',
            name='modelM',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mysilantapp.modelmachine'),
        ),
        migrations.AddField(
            model_name='machine',
            name='modelSA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mysilantapp.modelsteeringaxle'),
        ),
        migrations.AddField(
            model_name='machine',
            name='modelT',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mysilantapp.modeltransmission'),
        ),
        migrations.AddField(
            model_name='machine',
            name='userClient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machine',
            name='userService',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysilantapp.servicecompany'),
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRejection', models.DateField()),
                ('failDescription', models.CharField(max_length=128)),
                ('spareParts', models.CharField(max_length=128)),
                ('dateRecovery', models.DateField()),
                ('downtime', models.PositiveIntegerField(blank=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysilantapp.machine')),
                ('recMethod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysilantapp.recoverymethod')),
                ('typeFailure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysilantapp.typefailure')),
            ],
        ),
        migrations.AddField(
                    model_name='servicecompany',
                    name='user',
                    field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                    preserve_default=False,
        ),
        migrations.CreateModel(
                    name='UserSilant',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('categoryType', models.CharField(choices=[('MG', 'Менеджер'), ('CL', 'Клиент'), ('SK', 'Сервисная компания')], max_length=2)),
                        ('silUser', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
        ),
        migrations.AlterField(
                    model_name='servicecompany',
                    name='user',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysilantapp.usersilant'),
        ),
        migrations.AlterField(
                    model_name='machine',
                    name='userClient',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysilantapp.usersilant'),
        ),
        migrations.AlterField(
                    model_name='machine',
                    name='userClient',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AlterField(
                    model_name='machine',
                    name='userService',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
                    model_name='machine',
                    name='userService',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service', to='mysilantapp.servicecompany'),
        ),
        migrations.AlterField(
                    model_name='maintenance',
                    name='type',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mysilantapp.typemaintenance'),
        ),
        migrations.AddField(
                    model_name='maintenance',
                    name='operTime',
                    field=models.PositiveIntegerField(default=0),
                    preserve_default=False,
        ),
        migrations.AddField(
                    model_name='claim',
                    name='operTime',
                    field=models.PositiveIntegerField(default=0),
                    preserve_default=False,
        ),
        migrations.AlterField(
                    model_name='machine',
                    name='userClient',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client', to='mysilantapp.usersilant'),
        ),
        operations = [
                migrations.AlterField(
                    model_name='usersilant',
                    name='categoryType',
                    field=models.CharField(choices=[('Менеджер', 'Менеджер'), ('Клиент', 'Клиент'), ('Сервисная компания', 'Сервисная компания')], max_length=18),
        ),
        migrations.AlterField(
                    model_name='usersilant',
                    name='categoryType',
                    field=models.CharField(choices=[('MG', 'Менеджер'), ('CL', 'Клиент'), ('SK', 'Сервисная компания')], max_length=2),
        ),
        migrations.AlterField(
                    model_name='modeldriveaxle',
                    name='description',
                    field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
                    model_name='modelengine',
                    name='description',
                    field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
                    model_name='modelmachine',
                    name='description',
                    field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
                    model_name='modelsteeringaxle',
                    name='description',
                    field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
                    model_name='modeltransmission',
                    name='description',
                    field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
                    model_name='recoverymethod',
                    name='description',
                    field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
                    model_name='servicecompany',
                    name='description',
                    field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
                    model_name='typefailure',
                    name='description',
                    field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
                    model_name='typemaintenance',
                    name='description',
                    field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
                    model_name='modeldriveaxle',
                    name='description',
                    field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
                    model_name='modelengine',
                    name='description',
                    field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
                    model_name='modelmachine',
                    name='description',
                    field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
                    model_name='modelsteeringaxle',
                    name='description',
                    field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
                    model_name='modeltransmission',
                    name='description',
                    field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
                    model_name='recoverymethod',
                    name='description',
                    field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
                    model_name='servicecompany',
                    name='description',
                    field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
                    model_name='typefailure',
                    name='description',
                    field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
                    model_name='typemaintenance',
                    name='description',
                    field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
